---
comment:
  image:
    repository: frodox/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: frodox/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: frodox/ui
    tag: latest
  service:
    externalPort: 9292
