global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
    - channel: '#frodox-alertmanager'
