---
version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    restart: always
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      front_net:

  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    restart: always
    networks:
      back_net:
      front_net:
        aliases:
          - post

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    restart: always
    networks:
      back_net:
      front_net:
        aliases:
          - comment


volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
