{
 "title": "UI_service_monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "HTTP response time 95th percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_latency_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP requests with Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\", kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "graph",
   "description": "ALL HTTP Requests that UI service receives",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=\"200\", kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  }
 ]
}