---
service:
  type: NodePort
  port: 80
  annotations: {}
  labels: {}

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  path: /
  hosts:
    - reddit-grafana
  tls: []

adminUser: admin
adminPassword: admin
