---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: reddit
    component: ui

spec:
  type: NodePort
  ports:
    - port: 9292       # порт, для доступа к сервису изнутри k8s
      nodePort: 32092  # порт, для доступа к сервису снаружи кластера
      protocol: TCP
      targetPort: 9292
  selector:
    app: reddit
    component: ui
